### ISSUE TITLE
Define objects numer at type leve

### ISSUE THREAD

**Issue by mk-5** [mk-5/polygonal-io#19]
Goal: limit objects number per type, like "one public interface allowed"

Improvement proposal:

```
polygon:
  packagePrivate: -1
  packages:
    dto:
      public:
        class: 1
        interface: 1
    port:
      types: ['interface']
      public: -1
```
